server:
  port: 8081

app:
  asset-base-url: http://localhost:8081
  asset-storage-path: D:/Project/GameValutProject/game-assets


spring:
  application:
    name: GameWorkshop-service
  datasource:
    url: jdbc:postgresql://localhost:5432/game_workshop_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 210MB
      enabled: true

mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  type-aliases-package: com.gameworkshop.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
