server:
  port: 8081

app:
  asset-base-url: http://localhost:8081
  asset-storage-path: D:/Project/GameValutProject/game-assets

spring:
  application:
    name: GameVault-Developer-Service
  datasource:
    url: jdbc:postgresql://localhost:12010/gamevault_developer_db
    username: gamevault_developer_user
    password: gamevault_developer_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  data:
    redis:
      host: localhost
      port: 12013
      database: 0
      timeout: 2000

mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  type-aliases-package: com.gameworkshop.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
